// Generated by SandPiper(TM) 1.9-2018/02/11-beta from Redwood EDA.
// (Installed here: /home/devel/SandPiper_1.9-2018_02_11-beta_distro.)
// Redwood EDA does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


`include "sandpiper_gen.vh"





//
// Signals declared top-level.
//

// For $num1.
logic [3:0] L0_num1_a0;

// For $num2.
logic [3:0] L0_num2_a0;

// For $out.
logic [7:0] L0_out_a0;



generate

   // For signal $num1, which had no assignment.
   assign L0_num1_a0[3:0] = 'x;

   // For signal $num2, which had no assignment.
   assign L0_num2_a0[3:0] = 'x;



endgenerate




//
// Debug Signals
//

generate

   if (1) begin : DEBUG_SIGS

      logic [3:0] \@0$num1 ;
      assign \@0$num1 = L0_num1_a0;
      logic [3:0] \@0$num2 ;
      assign \@0$num2 = L0_num2_a0;
      logic [7:0] \@0$out ;
      assign \@0$out = L0_out_a0;


   end

endgenerate




generate   // This is awkward, but we need to go into 'generate' context in the line that `includes the declarations file.
