`line 2 "top.tlv" 0 //_\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.9-2018/02/11-beta
`include "sp_default.vh" //_\SV
module	ppio(i_dir, io_data, i_data, o_data);
   parameter	W=8;
	input			i_dir;
	inout	[(W-1):0]	io_data;
	input	[(W-1):0]	i_data;
	output	[(W-1):0]	o_data;
	genvar	k;
	generate for(k=0; k<W; k = k+1)
	begin : GEN_INOUT
		SB_IO #(.PULLUP(1'b0),
			.PIN_TYPE(6'b101001))
			theio(
				.OUTPUT_ENABLE(!i_dir),
				.PACKAGE_PIN(io_data[k]),
				.D_OUT_0(i_data[k]),
				.D_IN_0( o_data[k])
			);
	end endgenerate

   // =========================================
   // Welcome!  Try the tutorials via the menu.
   // =========================================

   // Default Makerchip TL-Verilog Code Template
   
   // Macro providing required top-level module definition, random
   // stimulus support, and Verilator config.
   //m4_makerchip_module   // (Expanded in Nav-TLV pane.)
`include "ppio_gen.sv" //_\TLV
   //$reset = *reset;
   assign L0_i_dir_a0 = i_dir;

   //...

   // Assert these to end simulation (before Makerchip cycle limit).
   assign passed = cyc_cnt > 40;
   assign failed = 1'b0; endgenerate
//_\SV
   endmodule
