`line 2 "top.tlv" 0 //_\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.9-2018/02/11-beta
`include "sp_default.vh" //_\SV
   // A simple example of a SV testbench and a TLV DUT.
   // Note that Verilator (compiler/simulator) only supports synthesizable SystemVerilog.

   // Testbench.
   module top(input logic clk, input logic reset, input logic [31:0] cyc_cnt, output logic passed, output logic failed);    /* verilator lint_save */ /* verilator lint_off UNOPTFLAT */  bit [256:0] RW_rand_raw; bit [256+63:0] RW_rand_vect; pseudo_rand #(.WIDTH(257)) pseudo_rand (clk, reset, RW_rand_raw[256:0]); assign RW_rand_vect[256+63:0] = {RW_rand_raw[62:0], RW_rand_raw};  /* verilator lint_restore */  /* verilator lint_off WIDTH */ /* verilator lint_off UNOPTFLAT */  // Expanded in Nav-TLV pane.
      logic run;          // Assert to start the series.
      logic [31:0] val;   // The value from the Fibonacci Series.

      assign run = cyc_cnt >= 5;
      dut dut(clk, reset, run, val);

      // Pass if Fibinocci value is correct after hardcoded # cycles; fail o/w.
      assign passed = cyc_cnt == 32'h10 && val == 32'h179;
      assign failed = cyc_cnt >  32'h10;
   endmodule


   // DUT.
   module dut(input logic clk, input logic reset, input logic run, output logic [31:0] val);
`include "top_gen.sv" //_\TLV
   assign L0_reset_a0 = reset;

   // Fibonacci.
   assign L0_val_a0[31:0] = (L0_reset_a0 || ! run) ? 1 : L0_val_a1 + L0_val_a2;
   assign val = L0_val_a0; endgenerate
//_\SV
   endmodule
