// Generated by SandPiper(TM) 1.9-2018/02/11-beta from Redwood EDA.
// (Installed here: /home/devel/SandPiper_1.9-2018_02_11-beta_distro.)
// Redwood EDA does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


`include "sandpiper_gen.vh"





//
// Signals declared top-level.
//

// For $reset.
logic L0_reset_a0;

// For |sdram$refresh_clk.
logic [9:0] SDRAM_refresh_clk_a0,
            SDRAM_refresh_clk_a1,
            SDRAM_refresh_clk_a2,
            SDRAM_refresh_clk_a3,
            SDRAM_refresh_clk_a4,
            SDRAM_refresh_clk_a5;



generate


   //
   // Scope: |sdram
   //

      // For $refresh_clk.
      always_ff @(posedge clk) SDRAM_refresh_clk_a1[9:0] <= SDRAM_refresh_clk_a0[9:0];
      always_ff @(posedge clk) SDRAM_refresh_clk_a2[9:0] <= SDRAM_refresh_clk_a1[9:0];
      always_ff @(posedge clk) SDRAM_refresh_clk_a3[9:0] <= SDRAM_refresh_clk_a2[9:0];
      always_ff @(posedge clk) SDRAM_refresh_clk_a4[9:0] <= SDRAM_refresh_clk_a3[9:0];
      always_ff @(posedge clk) SDRAM_refresh_clk_a5[9:0] <= SDRAM_refresh_clk_a4[9:0];




endgenerate




//
// Debug Signals
//

generate

   if (1) begin : DEBUG_SIGS

      logic  \@0$reset ;
      assign \@0$reset = L0_reset_a0;

      //
      // Scope: |sdram
      //
      if (1) begin : \|sdram 
         logic [9:0] \@0$refresh_clk ;
         assign \@0$refresh_clk = SDRAM_refresh_clk_a0;
      end


   end

endgenerate




generate   // This is awkward, but we need to go into 'generate' context in the line that `includes the declarations file.
