// Generated by SandPiper(TM) 1.9-2018/02/11-beta from Redwood EDA.
// (Installed here: /home/devel/SandPiper_1.9-2018_02_11-beta_distro.)
// Redwood EDA does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


`include "sandpiper_gen.vh"





//
// Signals declared top-level.
//

// For $reset.
logic L0_reset_a0;

// For $val.
logic [15:0] L0_val_a0,
             L0_val_a1,
             L0_val_a2;



generate

   // For $val.
   always_ff @(posedge clk) L0_val_a1[15:0] <= L0_val_a0[15:0];
   always_ff @(posedge clk) L0_val_a2[15:0] <= L0_val_a1[15:0];



endgenerate




generate   // This is awkward, but we need to go into 'generate' context in the line that `includes the declarations file.
